name: Multiple Jobs (Build, Test and Deploy)

on:
    push

jobs:
    build_job_1:
        runs-on: ubuntu-latest
        steps:
            - name: Install cowsay
              run: sudo apt-get install cowsay -y

            - name: Execute cowsay CMD
              run: cowsay -f dragon "Run for cover, I am a Dragon" >> dragon.txt

            - name: sleep for 30s
              run: sleep 30

    test_job_2:
        runs-on: ubuntu-latest
        steps:
            - name: Sleep for 10s
              run: sleep 10

            - name: Test Files exist
              run: grep -i "dragon" dragon.txt


    deploy_job_3:
        runs-on: ubuntu-latest
        steps:
            - name: Read File
              run: cat dragon.txt

            - name: Deploy
              run: echo Deploying...........
